version: "3"

volumes: 
  logs:

services:
  app:
    image: app
    container_name: java_app
    ports:
      - "8765:8765"

  web:
    build: ./angular-prometheus-exporter
    container_name: web
    image: web
    ports:
      - "80:80"
  nginx-exporter:
    image: "nginx/nginx-prometheus-exporter:latest"
    command: ["-nginx.scrape-uri=http://web:80/metrics"]
    ports:
      - "9113:9113"
        #  app:
        #    build: .
        #    volumes:
        #    - .:/app
        #    - ~/.m2:/root/.m2
        #    working_dir: /app
        #    command: bash -c "mvn clean package && java -jar target/healthcheck-prometheus-1.0-SNAPSHOT-jar-with-dependencies.jar"
        #    ports:
        #    - "8080:8080"
        #    depends_on:
        #    - mysqld
  python-application:
    build:
      context: ./python-application
    container_name: python-application
    image: python-application
    ports:
      - "81:5000"

  promtail:
    image: grafana/promtail:latest
    volumes:
      - logs:/logs/
      - ./config:/mnt/config
      - ./data/promtail:/mnt/var
      - /var/log:/var/log
    command: -config.file=/mnt/config/promtail-config-docker.yaml
    ports:
      - "9081:9080"
    restart: "always"

  # The Loki database for storing logs.
  #
  loki:
    image: grafana/loki:latest
    user: root
    volumes:
      - ./config:/mnt/config
      - ./data/loki-data:/tmp/loki
      - ./data/loki-wal:/tmp/wal
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"
    restart: "always"

  #
  # Prometheus
  #
  prometheus:
    image: prom/prometheus
    #
    # Not thrilled with having to run as root in the container, but trying
    # to run this in a Linux VM has permission issues, since Docker commands
    # are normally run as root...
    #
    user: root
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: "always"
    links:
      - mysqld-exporter
        #      - node_exporter


  #
  # Grafana, for viewing via the UI.
  #
  grafana:
    image: grafana/grafana:latest
    # Running this as root for the same reason Prometheus is running as root.
    user: root
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    restart: "always"

  mysqld:
    image: mysql:5.7
    container_name: mysqld
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_ROOT_PASSWORD: myRootPassword123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - ~/var/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysqld-exporter
    restart: unless-stopped
    command:
      - "--mysqld.username=root:myRootPassword123"
      - "--mysqld.address=172.31.13.248:3306"
    ports:
      - 9104:9104
    links:
      - mysqld
    depends_on:
      - mysqld

        #  node_exporter:
        #    image: quay.io/prometheus/node-exporter
        #    container_name: node_exporter
        #    command: "--path.rootfs=/host"
        #    pid: host
        #    restart: "always"
        #    volumes:
        #      - /:/host:ro,rslave

        #networks:
        #default:
        #driver: bridge
